name: "🐛 Bug Report"
description: "버그나 예기치 못한 동작을 제보합니다."
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: "문제 요약"
      placeholder: "예: 홈페이지 배포 시 500 에러 발생"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "재현 방법"
      description: "문제가 발생한 과정을 단계별로 설명해주세요."
      placeholder: |
        1. 홈페이지 빌더에서 '배포하기' 클릭
        2. 응답 지연 발생
        3. 배포 실패 메시지 확인

  - type: textarea
    id: expected
    attributes:
      label: "예상 동작"
      placeholder: "예: 정상적으로 K-PaaS에 업로드 및 배포되어야 함"

  - type: textarea
    id: environment
    attributes:
      label: "환경 정보"
      description: "테스트 환경 정보를 입력해주세요 (브라우저, OS, 브랜치 등)"
      placeholder: "예: Chrome 119 / macOS / main 브랜치"

  - type: checkboxes
    id: severity
    attributes:
      label: "심각도"
      options:
        - label: "🟥 Critical (서비스 불가 수준)"
        - label: "🟧 Major (주요 기능 오류)"
        - label: "🟨 Minor (경미한 버그)"